version: "3.0"
services:
  core_api:
    build: .
    image: core:core
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "8080:8080"
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- uwsgi --http :8080 --module application:application --enable-threads
  redis:
    image: redis:5.0.7-alpine
    expose:
      - 6379
  celery_worker:
    image: core:core
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A app.celery worker --loglevel=INFO
    env_file:
      - .env
    volumes:
      - .:/src
    depends_on:
      - redis
      - core_api
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - redis
      - celery_worker
